### ISSUE TITLE
How to make a orig.zip and mod.zip file?

### ISSUE THREAD

**Issue by R1310328554** [breenmachine/HPwn#2]
Hi, hacker:

What the README wrote is :
python hp_solution_patcher.py orig.bdl orig.zip mod.zip

Now , I have a xxx.bdl, However, how can make a  orig.zip and mod.zip file from BDL? Especially the orig.zip. Can I just unzip the BDL to create a orig.zip?

**Comment by R1310328554** [comment]
the err log is :

Garbage Bytes:33854
Diff: 808
Garbage Bytes:33046
Garbage Bytes CRC32: 7edc6e27
Original CRC-32: 4424F94B
Computed and wrote patch
New CRC-32 successfully verified
Traceback (most recent call last):
  File "hp_solution_patcher.py", line 230, in <module>
    errmsg = main(sys.argv[1:])
  File "hp_solution_patcher.py", line 53, in main
    idx=f.index(struct.pack("<I",original_crc32))+4
ValueError: substring not found
